### PR TITLE
Rename _Contract -> Contract. API documentation updates.

### LINKED ISSUE #37: Expose _Contract
### What was wrong?

Currently `web3.contract._Contract` is privateish It would be useful to expose this for static analysis to help IDE auto completion.

I'd suggest renaming `_Contract` to `Contract` or `ContractBase` and then exposing it in necessary `__init__` modules.

#### Cute Animal Picture

moo

### PR DESCRIPTION
**Pull request by miohtama**
### What was wrong?

_Contract is privateish and thus might be ignored by static analysis tools.

This fixes #37 

### How was it fixed?

_Contact -> Contract rename.

Also includes bunch of API documentation updates.

Test passed locally on Py 2.7, but not on Py 3.x. Let's see what Travis says.

#### Cute Animal Picture

koala

### CODE REVIEW

**Comment by pipermerriam** [comment]
A few linting errors and I'll get this merged.

```
/home/travis/build/pipermerriam/web3.py/web3/contract.py:131:101: E501 line too long (110 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:157:101: E501 line too long (102 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:159:101: E501 line too long (110 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:161:101: E501 line too long (107 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:166:101: E501 line too long (108 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:371:101: E501 line too long (109 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:412:101: E501 line too long (113 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:443:101: E501 line too long (115 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:526:101: E501 line too long (111 > 100 characters)

/home/travis/build/pipermerriam/web3.py/web3/contract.py:532:5: E303 too many blank lines (2)
```

**Comment by miohtama** [comment]
Is linting part of tox?

**Comment by miohtama** [comment]
Done!

**Comment by pipermerriam** [comment]
I resolved the merge conflict in #44 and will merge these changes there.

**Pull request closed without merging**
