### PR TITLE
Resolve ENS names to addresses

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

It was cumbersome to resolve names manually before using them throughout the web3 module. See #342 

### How was it fixed?

Detect .eth names and resolve them anywhere that addresses are used.

Three main entry points:
 * middleware that intercepts calls like `eth_getBalance` and replaces ENS name arguments with the address that they resolve to. Another example: the `to` & `from` fields in `eth_sendTransaction`
 * contract initialization - store the name and resolve it when you interact with the contract
 * accept ENS names in address-typed arguments to contract calls/transactions, and resolve those names before invoking

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
If you'll start using the "Ready for Review" label it'll help me do drive-by checks on things that need review.

**Comment by carver** [comment]
Sounds good, will do. It's ready for a look now.

**Comment by carver** [comment]
Okay, TODO:

- [ ] explore backend pattern for ENS
- [ ] accept any TLD (using `addr.startswith('0x') and '.' not in addr` to decide if address, otherwise test if valid ENS name)

**Comment by carver** [comment]
I didn't add an extra interface layer, but you can easily swap out ENS implementations in the web3 instance now. All usages (including the middleware and contracts) use the ens instance in the web3 object, so it's pretty painless to swap it out, even temporarily. Any objections to that approach before I merge @pipermerriam ?

If no comment by tomorrow afternoon, I'll assume we're good to go. Then we can cut the first v4-beta release!

**Comment by pipermerriam** [comment]
:shipit:

**Pull request merged**
